//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_Monitoring_Commette_DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CM_Monitorring_CommitteEntities : DbContext
    {
        public CM_Monitorring_CommitteEntities()
            : base("name=CM_Monitorring_CommitteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Progress_Commette_Gis> tbl_Progress_Commette_Gis { get; set; }
        public virtual DbSet<tbl_progress_Commette_raw> tbl_progress_Commette_raw { get; set; }
    }
}
