//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_Monitoring_Commette_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_progress_Commette_raw
    {
        public int id { get; set; }
        public string data_json { get; set; }
        public Nullable<System.DateTime> db_date_time { get; set; }
        public string app_version { get; set; }
        public string imei { get; set; }
        public int local_id { get; set; }
        public string unique_code { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string user_role { get; set; }
        public Nullable<bool> Added { get; set; }
    }
}
