//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_Monitoring_Commette_DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Progress_Commette_Gis
    {
        public int Id { get; set; }
        public Nullable<int> tehsilId { get; set; }
        public Nullable<int> auto_pk { get; set; }
        public Nullable<int> quality_of_work { get; set; }
        public Nullable<int> DivisonId { get; set; }
        public string lng { get; set; }
        public string remarks { get; set; }
        public Nullable<int> ucId { get; set; }
        public Nullable<int> serial_no_ADP { get; set; }
        public string col_a { get; set; }
        public string col_b { get; set; }
        public string data_captured_from_app_version { get; set; }
        public string username { get; set; }
        public Nullable<int> districtId { get; set; }
        public string col_e { get; set; }
        public string col_c { get; set; }
        public string col_d { get; set; }
        public Nullable<int> CommitteId { get; set; }
        public string userId { get; set; }
        public string lat { get; set; }
        public string ProjectName { get; set; }
        public string imei { get; set; }
        public string unique_code { get; set; }
        public string uc_name { get; set; }
        public Nullable<System.DateTime> date_time_mobile { get; set; }
        public string district_name { get; set; }
        public Nullable<int> uc_available_status { get; set; }
        public string tehsil_name { get; set; }
        public Nullable<int> tbl_progress_raw_id { get; set; }
        public Nullable<System.DateTime> db_date_time { get; set; }
        public Nullable<int> local_id { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string user_role { get; set; }
    }
}
