//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tehsil
    {
        public int Tehsil_ID { get; set; }
        public string Tehsil_Name { get; set; }
        public Nullable<int> Distt_ID { get; set; }
    }
}
