//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdpBook_multipleDist
    {
        public int auto_adp_Multiple_dist_id { get; set; }
        public Nullable<int> auto_adp_serial_id { get; set; }
        public Nullable<int> Distt_ID { get; set; }
    }
}
