//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adp_survey
    {
        public int id { get; set; }
        public string scheme_id { get; set; }
        public string sub_scheme_id { get; set; }
        public string component_id { get; set; }
        public string sub_component_id { get; set; }
        public byte[] data_time { get; set; }
        public string pic_path { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
