//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ADP_Serial
    {
        public int auto_adp_serial_id { get; set; }
        public Nullable<int> auto_ADP_id { get; set; }
        public string serial_no_ADP { get; set; }
        public Nullable<double> Allocation { get; set; }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }
        public Nullable<double> yearly_total_allocation { get; set; }
        public Nullable<bool> approved_schemes { get; set; }
        public Nullable<int> auto_Sector_id { get; set; }
        public Nullable<int> auto_SubSector_ID { get; set; }
        public Nullable<int> auto_Dept_Id { get; set; }
        public Nullable<int> Div_ID { get; set; }
        public Nullable<int> Distt_ID { get; set; }
        public string ProjectCode_revenue { get; set; }
        public Nullable<double> local_Capital { get; set; }
        public Nullable<double> local_Rev { get; set; }
        public Nullable<double> FAid_Cap { get; set; }
        public Nullable<double> FAid_Rev { get; set; }
        public Nullable<double> Total_Cap { get; set; }
        public Nullable<double> Total_Rev { get; set; }
        public string Scheme_Status { get; set; }
        public string old_Gsno { get; set; }
        public Nullable<bool> mneBit { get; set; }
        public Nullable<int> Prov_id { get; set; }
        public Nullable<int> Tehsil_id { get; set; }
        public Nullable<double> est_cost { get; set; }
        public Nullable<double> expenditure_cost { get; set; }
        public string SchemeCode { get; set; }
    }
}
