//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_mne_master
    {
        public int auto_id_mne_master { get; set; }
        public Nullable<int> auto_Pc1_id { get; set; }
        public Nullable<System.DateTime> EV_Date_Of_Evaluation { get; set; }
        public string EV_Firm_Name_Evaluating { get; set; }
        public string EV_EvaluationReport_Attachment { get; set; }
        public Nullable<System.DateTime> EV_Completion_Date { get; set; }
        public Nullable<System.DateTime> EV_PCIV_Submission_Date { get; set; }
        public string EV_PCIV_Attachment { get; set; }
        public Nullable<System.DateTime> EV_PostProjectEvaluation_date { get; set; }
        public string EV_Firm_Name { get; set; }
        public string EV_PostProjectEvaluation_Report_Attachment { get; set; }
        public string Ev_QulaityOfWork { get; set; }
        public Nullable<System.DateTime> Apr_SubmissionDate { get; set; }
        public Nullable<System.DateTime> Apr_PrePDWP_MeetingDate { get; set; }
        public Nullable<System.DateTime> Apr_PDWP_meetingDate { get; set; }
        public string Apr_PDWP_Attachment { get; set; }
        public Nullable<System.DateTime> Apr_ClearanceLetterDate_Pndd { get; set; }
        public string Apr_ClearanceLetter_Attachment { get; set; }
        public Nullable<System.DateTime> Apr_Admn_Approval_Date { get; set; }
        public string Apr_AA_Attachment { get; set; }
        public Nullable<System.DateTime> Apr_TechnicalSanctioned_Date { get; set; }
        public Nullable<double> Apr_TS_Amount { get; set; }
        public string Apr_TS_Attachemnt { get; set; }
        public Nullable<System.DateTime> Apr_FundAllocationDate_Pndd { get; set; }
        public Nullable<double> Apr_FundAllocationAmount_Pndd { get; set; }
        public string Apr_FundAllocation_Pndd_Attachment { get; set; }
        public Nullable<System.DateTime> Apr_Fd_ReleaseDate { get; set; }
        public Nullable<double> Apr_Fd_ReleaseAmount { get; set; }
        public string Apr_Fd_Attacment { get; set; }
        public Nullable<System.DateTime> Apr_AdpAllocationDate { get; set; }
        public Nullable<double> Apr_AdpAllocationAmount { get; set; }
        public Nullable<double> Apr_PC1_AmountProposed { get; set; }
        public Nullable<double> Apr_PC1_AmountApproved { get; set; }
        public Nullable<System.DateTime> Apr_AuditCopyDate { get; set; }
        public Nullable<double> Apr_TS_AmountEstimated { get; set; }
        public string Apr_ADP_InformationPaper_Attachment { get; set; }
        public string Apr_PrePDWP_MOM_Attachment { get; set; }
    
        public virtual tbl_PC1_ADP_serial tbl_PC1_ADP_serial { get; set; }
    }
}
