//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_adp
    {
        public int auto_ADP_id { get; set; }
        public string ADP_name { get; set; }
    }
}
