//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Division
    {
        public int Div_ID { get; set; }
        public string Div_Name { get; set; }
        public string div_extent { get; set; }
        public string centroid { get; set; }
        public string Div_Code { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
    }
}
