//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Distt
    {
        public int Distt_ID { get; set; }
        public string Dist_Name { get; set; }
        public Nullable<int> Div_ID { get; set; }
        public string dis_extent { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public System.Data.Entity.Spatial.DbGeography geom_ { get; set; }
        public string Dist_Code { get; set; }
    }
}
