//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PC1_ADP_serial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PC1_ADP_serial()
        {
            this.tbl_mne_master = new HashSet<tbl_mne_master>();
        }
    
        public int auto_PC1_ADP_serial { get; set; }
        public Nullable<int> auto_adp_serial_id { get; set; }
        public int auto_pc1_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mne_master> tbl_mne_master { get; set; }
        public virtual tbl_PC1 tbl_PC1 { get; set; }
    }
}
