//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdpDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PC1
    {
        public int auto_pc1_id { get; set; }
        public string pc1_code { get; set; }
        public string pc1_prj_name { get; set; }
        public Nullable<int> auto_pc1_project_type { get; set; }
        public Nullable<int> auto_pc_type_id { get; set; }
        public Nullable<System.DateTime> plan_start_date { get; set; }
        public Nullable<System.DateTime> plan_end_date { get; set; }
        public Nullable<double> total_cost { get; set; }
        public Nullable<bool> is_plan_for_allPujab { get; set; }
        public string plan_complete_address { get; set; }
        public Nullable<int> auto_SponsorID { get; set; }
        public Nullable<bool> isMTDF { get; set; }
        public Nullable<bool> isADP { get; set; }
        public string Prj_incld_5_yr_specify { get; set; }
        public Nullable<bool> isBlockAllocation { get; set; }
        public string Prj_objective { get; set; }
        public string Prj_Justification { get; set; }
        public string DemandSupplyAnalysis { get; set; }
        public string FinancialBenefit { get; set; }
        public string EconomicBenefit { get; set; }
        public string Socialbenefit { get; set; }
        public string EmploymentGeneration { get; set; }
        public string EnvoirnmentImpact { get; set; }
        public string DelayImapact { get; set; }
        public string DecisionBenefit { get; set; }
        public string Certification { get; set; }
        public Nullable<int> Guestation_Period { get; set; }
        public Nullable<bool> isReturnedBack { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<int> auto_forum_id { get; set; }
        public Nullable<int> submitted_by_deptt { get; set; }
        public Nullable<int> auto_decision_id { get; set; }
        public Nullable<System.DateTime> data_entry { get; set; }
        public string attachment { get; set; }
        public Nullable<double> duration { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tbl_PC1_ADP_serial tbl_PC1_ADP_serial { get; set; }
    }
}
