//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDWP_Data_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDWP_WorkingPaper_DBEntities : DbContext
    {
        public PDWP_WorkingPaper_DBEntities()
            : base("name=PDWP_WorkingPaper_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FollowUp> FollowUps { get; set; }
        public virtual DbSet<Agenda> Agendas { get; set; }
    }
}
