//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_SchemesDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UC_SchemesEntities : DbContext
    {
        public UC_SchemesEntities()
            : base("name=UC_SchemesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Progress_Scheme_GIS> tbl_Progress_Scheme_GIS { get; set; }
        public virtual DbSet<tbl_progress_raw_monitoring> tbl_progress_raw_monitoring { get; set; }
        public virtual DbSet<Pm_Tbl_Main_Scheme> Pm_Tbl_Main_Scheme { get; set; }
        public virtual DbSet<tbl_UC_MC_Detail> tbl_UC_MC_Detail { get; set; }
        public virtual DbSet<tbl_SendSMS> tbl_SendSMS { get; set; }
        public virtual DbSet<tbl_progress_raw> tbl_progress_raw { get; set; }
        public virtual DbSet<tbl_raw_tpv> tbl_raw_tpv { get; set; }
        public virtual DbSet<tpv_progress> tpv_progress { get; set; }
    }
}
