//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_SchemesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pm_Tbl_Main_Scheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pm_Tbl_Main_Scheme()
        {
            this.tbl_Progress_Scheme_GIS = new HashSet<tbl_Progress_Scheme_GIS>();
            this.tpv_progress = new HashSet<tpv_progress>();
        }
    
        public int auto_Pm_Scheme_id { get; set; }
        public string name_Scheme { get; set; }
        public Nullable<int> auto_Sector_id { get; set; }
        public Nullable<int> auto_subSector_id { get; set; }
        public Nullable<int> SDG_id { get; set; }
        public Nullable<int> Prov_id { get; set; }
        public Nullable<int> Div_ID { get; set; }
        public Nullable<int> Distt_ID { get; set; }
        public Nullable<int> auto_na_constituency_id { get; set; }
        public Nullable<int> auto_pp_constituency_id { get; set; }
        public Nullable<int> auto_UC_Name_id { get; set; }
        public Nullable<int> auto_Uc_code_Detail_id { get; set; }
        public string LocationAddress { get; set; }
        public string code_universal { get; set; }
        public Nullable<int> auto_SponsorID { get; set; }
        public Nullable<int> Executing_Agency_ID { get; set; }
        public Nullable<int> auto_Dept_Id { get; set; }
        public Nullable<double> Estimated_Cost { get; set; }
        public Nullable<int> auto_forum_id { get; set; }
        public Nullable<System.DateTime> Date_Approval { get; set; }
        public string AttachmentMOM { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string objScheme { get; set; }
        public string AttachmentPC1 { get; set; }
        public string AA { get; set; }
        public Nullable<System.DateTime> AA_Date { get; set; }
        public string AA_No { get; set; }
        public Nullable<double> AA_Approved_cost { get; set; }
        public string TS { get; set; }
        public Nullable<System.DateTime> TS_Date { get; set; }
        public Nullable<System.DateTime> schementryDate { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<int> auto_package_id { get; set; }
        public Nullable<bool> ApprovedSchemes { get; set; }
        public Nullable<int> Auto_child_subSectorid { get; set; }
        public Nullable<bool> WorkOrderIssue { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<bool> ProcurementUnderProgress { get; set; }
        public Nullable<System.DateTime> TenderDate { get; set; }
        public string PefraProjectId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> SchemeInitiatedId { get; set; }
        public Nullable<System.DateTime> DDIC_Date { get; set; }
        public string WorkOrder_Attachment { get; set; }
        public string DDC_Attachment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Tehsil_Id { get; set; }
        public Nullable<int> UC_MC_Detail_Id { get; set; }
        public Nullable<int> UC_Type_Id { get; set; }
    
        public virtual Pm_Tbl_Main_Scheme Pm_Tbl_Main_Scheme1 { get; set; }
        public virtual Pm_Tbl_Main_Scheme Pm_Tbl_Main_Scheme2 { get; set; }
        public virtual Pm_Tbl_Main_Scheme Pm_Tbl_Main_Scheme11 { get; set; }
        public virtual Pm_Tbl_Main_Scheme Pm_Tbl_Main_Scheme3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Progress_Scheme_GIS> tbl_Progress_Scheme_GIS { get; set; }
        public virtual tbl_UC_MC_Detail tbl_UC_MC_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpv_progress> tpv_progress { get; set; }
    }
}
