//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_SchemesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SendSMS
    {
        public int Id { get; set; }
        public string Time { get; set; }
        public string Mobile { get; set; }
        public string Name { get; set; }
        public Nullable<int> Distt_Id { get; set; }
    }
}
