//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_SchemesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Progress_Scheme_GIS
    {
        public int auto_Pm_Scheme_id { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom { get; set; }
        public string file_path { get; set; }
        public Nullable<int> Div_ID { get; set; }
        public Nullable<int> Distt_ID { get; set; }
        public System.DateTime mobile_datetime { get; set; }
        public string remarks { get; set; }
        public string imei { get; set; }
        public int progress { get; set; }
        public int auto_mapping_id { get; set; }
        public Nullable<System.DateTime> db_datetime { get; set; }
        public string appversion { get; set; }
        public Nullable<int> local_id { get; set; }
        public string picture_two { get; set; }
        public string picture_three { get; set; }
        public string picture_four { get; set; }
        public Nullable<int> status_id { get; set; }
        public string Role { get; set; }
        public string User_name { get; set; }
        public Nullable<bool> bit_for_dd { get; set; }
        public string Quality_issue { get; set; }
        public string Time_delay_Issue { get; set; }
        public string Contractor_Issue { get; set; }
        public string Payment_Issue { get; set; }
        public string Consultant_Issue { get; set; }
        public string Land_Issue { get; set; }
        public string Drawing_Issue { get; set; }
        public string Other_Issue { get; set; }
        public Nullable<int> image_status_id { get; set; }
        public Nullable<int> Uc_Id { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string unique_code { get; set; }
        public Nullable<int> progress_raw_id { get; set; }
        public Nullable<int> progress_raw_monitoring_id { get; set; }
        public System.Data.Entity.Spatial.DbGeometry geom_new { get; set; }
        public string col_a { get; set; }
        public string col_b { get; set; }
        public string col_c { get; set; }
        public string col_d { get; set; }
        public string col_e { get; set; }
        public string designation_double_check { get; set; }
        public string data_captured_from_app_version { get; set; }
        public string need_designation_correction { get; set; }
        public Nullable<bool> qc_status { get; set; }
        public string qc_status_remarks { get; set; }
    
        public virtual Pm_Tbl_Main_Scheme Pm_Tbl_Main_Scheme { get; set; }
        public virtual tbl_UC_MC_Detail tbl_UC_MC_Detail { get; set; }
    }
}
