//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UC_SchemesDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UC_MC_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_UC_MC_Detail()
        {
            this.Pm_Tbl_Main_Scheme = new HashSet<Pm_Tbl_Main_Scheme>();
            this.tbl_Progress_Scheme_GIS = new HashSet<tbl_Progress_Scheme_GIS>();
            this.tpv_progress = new HashSet<tpv_progress>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UC_Type_Id { get; set; }
        public Nullable<int> Tehsil_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> UC_No { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pm_Tbl_Main_Scheme> Pm_Tbl_Main_Scheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Progress_Scheme_GIS> tbl_Progress_Scheme_GIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tpv_progress> tpv_progress { get; set; }
    }
}
