//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDWPLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PDWP_WorkingPaper_DBEntities : DbContext
    {
        public PDWP_WorkingPaper_DBEntities()
            : base("name=PDWP_WorkingPaper_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agenda> Agendas { get; set; }
        public virtual DbSet<SchemeAttachment> SchemeAttachments { get; set; }
    
        public virtual ObjectResult<Iris_Get_Agendas_Result> Iris_Get_Agendas(Nullable<int> month, Nullable<int> year, Nullable<int> province_id)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var province_idParameter = province_id.HasValue ?
                new ObjectParameter("province_id", province_id) :
                new ObjectParameter("province_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Iris_Get_Agendas_Result>("PDWP_WorkingPaper_DBEntities.Iris_Get_Agendas", monthParameter, yearParameter, province_idParameter);
        }
    
        public virtual ObjectResult<Iris_Get_Agenda_WorkingPapers_Result> Iris_Get_Agenda_WorkingPapers(Nullable<int> agenda_id)
        {
            var agenda_idParameter = agenda_id.HasValue ?
                new ObjectParameter("agenda_id", agenda_id) :
                new ObjectParameter("agenda_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Iris_Get_Agenda_WorkingPapers_Result>("PDWP_WorkingPaper_DBEntities.Iris_Get_Agenda_WorkingPapers", agenda_idParameter);
        }
    }
}
