//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDWPLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchemeAttachment
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AttachmentTypeId { get; set; }
        public Nullable<int> WorkingPaperId { get; set; }
        public Nullable<int> AgendaId { get; set; }
        public string Path { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public string LiveMonitoringDash { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    
        public virtual Agenda Agenda { get; set; }
    }
}
